# Generated by Django 6.0.2 on 2026-02-24 07:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Краткое описание объявления', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Подробное описание товара/услуги', verbose_name='Описание')),
                ('ad_type', models.CharField(choices=[('sale', 'Продам'), ('buy', 'Куплю'), ('rent', 'Сдам в аренду'), ('free', 'Отдам в хорошие руки'), ('handmade', 'Услуги мастера')], default='sale', max_length=20, verbose_name='Тип объявления')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Укажите цену (для "Продам", "Сдам в аренду")', max_digits=10, null=True, verbose_name='Цена')),
                ('phone', models.CharField(blank=True, help_text='Контактный телефон', max_length=20, verbose_name='Телефон для связи')),
                ('email', models.EmailField(blank=True, help_text='Контактный email', max_length=254, verbose_name='Email для связи')),
                ('address', models.CharField(blank=True, help_text='Улица, дом (опционально)', max_length=200, verbose_name='Адрес')),
                ('village', models.CharField(choices=[('bunyakovo', 'Буняково'), ('ryabtsevo', 'Рябцево'), ('other', 'Я из другого места')], default='bunyakovo', max_length=50, verbose_name='Населённый пункт')),
                ('moderation_status', models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', help_text='Статус проверки администратором', max_length=20, verbose_name='Статус модерации')),
                ('moderation_comment', models.TextField(blank=True, help_text='Причина отклонения (если отклонено)', verbose_name='Комментарий модератора')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать объявление в списке', verbose_name='Активно')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Поддерживаются форматы: JPG, PNG, WebP', upload_to='ads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (0 - первое)', verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявлений',
                'ordering': ['order', 'uploaded_at'],
                'constraints': [models.UniqueConstraint(fields=('advertisement', 'order'), name='unique_advertisement_image_order')],
            },
        ),
    ]
