# Generated by Django 6.0.2 on 2026-02-24 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя и отчество')),
                ('title', models.CharField(default='Настоятель храма', max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон для связи')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='church/priests/', verbose_name='Фотография')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Краткая биография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Священник',
                'verbose_name_plural': 'Священники',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье'), ('holiday', 'Праздничный день')], max_length=20, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата (необязательно)')),
                ('service_name', models.CharField(max_length=200, verbose_name='Название службы')),
                ('time', models.TimeField(verbose_name='Время начала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Расписание богослужения',
                'verbose_name_plural': 'Расписание богослужений',
                'ordering': ['day_of_week', 'date', 'order', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ChurchMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео')], default='photo', max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(upload_to='church/media/', verbose_name='Файл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='church/media/thumbnails/', verbose_name='Миниатюра (для видео)')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано (прошло модерацию)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('priest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.priest', verbose_name='Священник на фото/видео')),
            ],
            options={
                'verbose_name': 'Медиафайл церкви',
                'verbose_name_plural': 'Медиафайлы церкви',
                'ordering': ['-event_date', '-order'],
            },
        ),
        migrations.CreateModel(
            name='ChurchAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('announcement_type', models.CharField(choices=[('general', 'Общее объявление'), ('service', 'Объявление о службе'), ('event', 'Объявление о мероприятии'), ('prayer', 'Молитвенное объявление'), ('urgent', 'Срочное объявление')], default='general', max_length=20, verbose_name='Тип объявления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет (чем выше, тем выше в списке)')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('priest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.priest', verbose_name='Автор (батюшка)')),
            ],
            options={
                'verbose_name': 'Объявление от батюшки',
                'verbose_name_plural': 'Объявления от батюшки',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
