# Generated by Django 6.0.2 on 2026-02-24 07:34

import community.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео')], max_length=10, verbose_name='Тип')),
                ('file', models.FileField(help_text='Фото: до 5 МБ, Видео: до 100 МБ', upload_to=community.models.community_media_upload_path, verbose_name='Файл')),
                ('thumbnail', models.ImageField(blank=True, help_text='Миниатюра для видео', null=True, upload_to=community.models.community_thumbnail_upload_path, verbose_name='Превью')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('village', models.CharField(choices=[('bunyakovo', 'Буняково'), ('ryabtsevo', 'Рябцево'), ('all', 'Общее')], default='all', max_length=50, verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Медиа',
                'verbose_name_plural': 'Медиа',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UsefulPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации/службы')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('category', models.CharField(choices=[('emergency', 'Экстренные службы'), ('administration', 'Администрация'), ('medical', 'Медицинские'), ('transport', 'Транспорт'), ('utility', 'Коммунальные службы'), ('police', 'Полиция'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Полезный телефон',
                'verbose_name_plural': 'Полезные телефоны',
                'ordering': ['order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('news_type', models.CharField(choices=[('news', 'Новости'), ('important', 'Важная информация')], default='news', max_length=20, verbose_name='Тип записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет (чем выше, тем выше в списке)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость / Информация',
                'verbose_name_plural': 'Новости и информация',
                'ordering': ['-priority', '-published_at'],
            },
        ),
    ]
